### ISSUE TITLE
Compatibility with other Arduino boards?

### ISSUE THREAD

**Issue by tjanson** [Jonas-commits/Neo-Keyboard-Adapter#1]
First off, thank you very much for your work! I really appreciate anyone that lessens the pain of using an obscure keyboard layout on Windows machines. ;)

I’m wondering whether there’s a technical reason you chose the Pro Micro, or whether that’s simply what you happened to have available. Would it be a bad idea to use e.g. an Uno (with compatible shield of course) instead?

Also, am I understanding the "Limitations" section correctly in that all layers (or layers 1–4) are already supported? Because that would be amazing!

**Comment by Jonas-commits** [comment]
Hello,
The Arduino Pro Micro was used because of the following reasons:
    • USB Device Capability (can emulate an HID device)
    • USB Host capability with supported hardware
    • Pinning (The Micro Host Shield is almost pin-compatible)
    • Size 
    • Pricing (Arduino Pro Micro is around €4, the Micro Host shield is about €4, so total pricing for the setup is around €10)

An Arduino Uno does not have the ability to emulate an HID device and runs on 5V, therefore it cannot be used without additional hardware. Furthermore, it is bulky and expensive, so only disadvantages.
A valid alternative would be a Teensy, however, this drives up cost and is not pin-compatible at all to the USB Host Shield and therefore requires rewiring effort.

After a lot of optimization, the limitations which come from the hardware itself are neglilble. Everything works now (Layers 1-6, Pseudo Layer, and almost all compose sequences). The only problem is Unicode input under windows, which is very little supported by windows, the only way around this is to solve this in software again :)

**Comment by tjanson** [comment]
Makes sense. That’s great to hear.
